package view.component;

import java.awt.event.MouseListener;

/**
 *
 * @author hoaithu842
 */
public class ChatItem extends javax.swing.JPanel {

    /**
     * Creates new form UserItem
     */
    public ChatItem(String name) {
        initComponents();
        nameLabel.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avatarLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(250, 50));
        setMinimumSize(new java.awt.Dimension(250, 50));

        avatarLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user-avatar.png"))); // NOI18N

        nameLabel.setText("@username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(avatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(avatarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatarLabel;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables

    // Getters
    @Override
    public String getName() {
        return nameLabel.getText();
    }
    // Event Handlers
    public void addUsernameLabelMouseListener(MouseListener listenForClick) {
        nameLabel.addMouseListener(listenForClick);
    }
}
