package view.component;

import java.awt.event.MouseListener;

/**
 *
 * @author hoaithu842
 */
public class UserItem extends javax.swing.JPanel {

    /**
     * Creates new form UserItem
     */
    public UserItem(String username) {
        initComponents();
        usernameLabel.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userAvatarLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(250, 50));
        setMinimumSize(new java.awt.Dimension(250, 50));

        userAvatarLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user-avatar.png"))); // NOI18N

        usernameLabel.setText("@username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(userAvatarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userAvatarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel userAvatarLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

    // Getters
    public String getUsername() {
        return usernameLabel.getText();
    }
    // Event Handlers
    public void addUsernameLabelMouseListener(MouseListener listenForClick) {
        usernameLabel.addMouseListener(listenForClick);
    }
}
